from selenium import webdriver
from selenium.webdriver import ActionChains
# form selenium.webdriver import ActionChains
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By
import time
driver=webdriver.Chrome("E:\chromedrivers\chromedriver_win32 (5)\\chromedriver.exe")
driver.get("https://automationtesting.in")
driver.maximize_window()
driver.find_element(By.PARTIAL_LINK_TEXT,"Demo Site").click()
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[1]/div[1]/input').send_keys('RIYA')
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[1]/div[2]/input').send_keys('PALANDURKAR')
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[2]/div/textarea').send_keys(('NAGPUR'))
# driver.find_element(By.XPATH,'//*[@id="eid"]/input').send_keys('abcd@mkmklf')
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[4]/div/input').send_keys('6489498451')
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[5]/div/label[1]/input').click()
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[5]/div/label[2]/input').click()
# driver.find_element(By.ID,"checkbox1").click()
# driver.find_element(By.ID,"checkbox2").click()
# driver.find_element(By.ID,"msdd").click()
# time.sleep(6)
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[7]/div/multi-select/div[2]/ul/li[2]/a').click()
# select=Select(driver.find_element(By.XPATH,'//select[@id="Skills"]'))
# select.select_by_visible_text('C++')
# selectcountry=Select(driver.find_element(By.ID,"country"))
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[10]/div/span').click()
# driver.find_element(By.XPATH,"/html/body/span/sapn/span[1]/input").send_keys("India")
# time.sleep(8)
# driver.find_element(By.XPATH,'//*[@id="select2-country-results"]/li[1]').click()
# selyear=Select(driver.find_element(By.XPATH,'//select[@id="yearbox"]'))
# selyear.select_by_index(81)
# selmon=Select(driver.find_element(By.XPATH,'//select[@placeholder="Month"]'))
# selmon.select_by_index(5)
# seldate=Select(driver.find_element(By.XPATH,'//select[@id="daybox"]'))
# seldate.select_by_index(18)
# driver.find_element(By.ID,'firstpassword').send_keys("password")
# driver.find_element(By.XPATH,'//input[@id="secondpassword"]').send_keys("password")
# driver.find_element(By.XPATH,'//button[@id="submitbtn"]').click()
# time.sleep(5)
# actions=ActionChains(driver)
driver.find_element(By.PARTIAL_LINK_TEXT,'SwitchTo').click()
driver.find_element(By.PARTIAL_LINK_TEXT,'Alert').click()
driver.find_element(By.XPATH,'//button[@onclick="alertbox()"]').click()
alert=Alert(driver).accept()
driver.find_element(By.XPATH,'//a[@href="CancelTab"]').click()
driver.find_element(By.XPATH,'//button[@onclick="confirmbox()"]').click()
alert=Alert(driver).accept()
driver.find_element(By.XPATH,'//a[@href="#Textbox"]').click()
driver.find_element(By.XPATH,'//button[@class="btn btn-info"]').click()
alert=Alert(driver).accept()
driver.find_element(By.PARTIAL_LINK_TEXT,'SwitchTo').click()
driver.find_element(By.PARTIAL_LINK_TEXT,'Frames').click()
driver.find_element(By.XPATH,'//a[@href="#multiple"]').click()
driver.find_element(By.XPATH,'')

