from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support import expected_conditions as EC
import time
driver=webdriver.Chrome("E:\chromedrivers\chromedriver_win32 (5)\\chromedriver.exe")
driver.implicitly_wait(10)
driver.get("https://automationtesting.in/")
driver.find_element(By.PARTIAL_LINK_TEXT,"Demo Site").click()
action=ActionChains(driver)
driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[1]/div[1]/input').send_keys('RIYA')
driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[1]/div[2]/input').send_keys('PALANDURKAR')
driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[2]/div/textarea').send_keys(('NAGPUR'))
driver.find_element(By.XPATH,'//*[@id="eid"]/input').send_keys('abcd@mkmklf')
driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[4]/div/input').send_keys('6489498451')
driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[5]/div/label[1]/input').click()
driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[5]/div/label[2]/input').click()
driver.find_element(By.ID,"checkbox1").click()
driver.find_element(By.ID,"checkbox2").click()
select=Select(driver.find_element(By.ID,"country"))
time.sleep(2)
driver.find_element(By.XPATH,'//*[@id=basicBootstrapfrom"]/div[10]/div/span').click()
driver.find_element(By.XPATH,"/html/body/span/span/span[1]input").send_keys("Denmark")
driver.find_element(By.XPATH,'//*[@id="select2-country-container"]').click()
driver.find_element(By.ID,'//*[@id="msdd"]').click()
driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[7]/div/multi-select/div[2]/ul/li[2]/a').click()
driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[7]/div/multi-select/div[2]/ul/li[2]/a').click()
Select=Select(driver.find_element(By.XPATH,'//select[@id="Skills"]'))
Select.select_by_visible_text('C++')
selyear=Select(driver.find_element(By.XPATH,'//select[@id="yearbox"]'))
selyear.select_by_index(81)
selmon=Select(driver.find_element(By.XPATH,'//select[@placeholder="Month"]'))
selmon.select_by_index(5)
seldate=Select(driver.find_element(By.XPATH,'//select[@id="daybox"]'))
seldate.select_by_index(18)
driver.find_element(By.ID,'firstpassword').send_keys("password")
driver.find_element(By.XPATH,'//input[@id="secondpassword"]').send_keys("password")
driver.find_element(By.XPATH,'//button[@id="submitbtn"]').click()
time.sleep(1)
driver.find_element(By.ID,"msdd").click()
# time.sleep(6)
driver.find_element(By.XPATH,'//*[@id="//*[@id="basicBootstrapForm"]/div[7]/div/multi-select/div[2]/ul/li[2]/a').click()
driver.find_element(By.XPATH,'//*[@id="//*[@id="basicBootstrapForm"]/div[7]/div/multi-select/div[2]/ul/li[8]/a').click()
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[7]/div/multi-select/div[2]/ul/li[5]/label').click()