from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
import time
driver=webdriver.Chrome("D:\\selenium\\chromedriver_win32\\chromedriver.exe")
driver.get("https://automationtesting.in")
driver.maximize_window()
driver.find_element(By.PARTIAL_LINK_TEXT,"Demo Site").click()
# time.sleep(3)
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[1]/div[1]/input').send_keys('rutu')
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[1]/div[2]/input').send_keys('PALANDURKAR')
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[2]/div/textarea').send_keys(('NAGPUR'))
# driver.find_element(By.XPATH,'//*[@id="eid"]/input').send_keys('abcd@mkmklf')
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[4]/div/input').send_keys('6489498451')
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[5]/div/label[1]/input').click()
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[5]/div/label[2]/input').click()
# driver.find_element(By.ID,"checkbox1").click()
# driver.find_element(By.ID,"checkbox2").click()
# Select=Select(driver.find_element(By.XPATH,'//select[@id="Skills"]'))
# Select.select_by_visible_text('C++')
# time.sleep(2)
selectcountry=Select(driver.find_element(By.ID,"country"))
driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[10]/div/span').click()
driver.find_element(By.XPATH,"
driver.find_element(By.XPATH,'//*[@id="select2-country-results"]/li[5]').click()
# driver.find_element(By.ID,'id="msdd').click()
# driver.find_element(By.XPATH,'//*[@id="basicbootstrapform"]/div[7]/div/multi-select/div[2]/ul/li[2]/a').click()
# driver.find_element(By.XPATH,'//*[@id="basicbootstrapform"]/div[7]/div/multi-select/div[2]/ul/li[8]/a').click()
# driver.find_element(By.XPATH,'//*[@id="basicBootstrapForm"]/div[7]/div/multi-select/div[2]/ul/li[5]/label').click()
# selyear=Select(driver.find_element(By.XPATH,'//select[@id="yearbox"]'))
# selyear.select_by_index(81)
# selmon=Select(driver.find_element(By.XPATH,'//select[@placeholder="Month"]'))
# selmon.select_by_index(5)
#
# seldate=Select(driver.find_element(By.XPATH,'//select[@id="daybox"]'))
# seldate.select_by_index(18)
# driver.find_element(By.ID,'firstpassword').send_keys("password")
# driver.find_element(By.XPATH,'//input[@id="secondpassword"]').send_keys("password")
# driver.find_element(By.XPATH,'//button[@id="submitbtn"]').click()
# # time.sleep(1)